import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

export const generateTNAPDF = (data, milestones, summary) => {
  const doc = new jsPDF({
    orientation: 'landscape',
  });
  const date = new Date().toLocaleDateString();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(26, 60, 92); // Navy
  doc.text('TNA Calendar', 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Style: ${data.styleName || 'N/A'} | Ship Date: ${data.shipDate ? format(new Date(data.shipDate), 'dd MMM yyyy') : 'N/A'}`, 14, 30);
  doc.text('JM Jain LLP - Confidential', 240, 22);

  // Summary
  doc.setFontSize(12);
  doc.setTextColor(232, 98, 42); // Orange
  doc.text(`Summary: ${summary.onTrack} On Track | ${summary.atRisk} At Risk | ${summary.overdue} Overdue | ${summary.complete} Complete`, 14, 45);

  // Milestone Table
  autoTable(doc, {
    startY: 55,
    head: [['Milestone', 'Target Date', 'Actual Date', 'Status', 'Days Left', 'Notes']],
    body: milestones.map(m => [
      m.name,
      format(m.date, 'dd MMM yyyy'),
      m.actualDate ? format(new Date(m.actualDate), 'dd MMM yyyy') : '-',
      m.status.toUpperCase().replace('-', ' '),
      m.isComplete ? 'DONE' : `${Math.ceil((m.date - new Date()) / (1000 * 60 * 60 * 24))} days`,
      m.notes || ''
    ]),
    theme: 'striped',
    headStyles: { fillColor: [26, 60, 92] },
    columnStyles: {
      3: { fontStyle: 'bold' },
      5: { cellWidth: 50 }
    },
    didParseCell: function(data) {
      if (data.column.index === 3) {
        const status = data.cell.raw;
        if (status === 'COMPLETE') data.cell.styles.textColor = [34, 197, 94];
        if (status === 'COMPLETE LATE') data.cell.styles.textColor = [239, 68, 68];
        if (status === 'OVERDUE') data.cell.styles.textColor = [239, 68, 68];
        if (status === 'AT RISK') data.cell.styles.textColor = [249, 115, 22];
        if (status === 'ON TRACK') data.cell.styles.textColor = [59, 130, 246];
      }
    }
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by GarmentCalc Tool - JM Jain LLP', 14, 200);
    doc.text(`Page ${i} of ${pageCount}`, 270, 200);
  }

  doc.save(`TNA_${data.styleName || 'Style'}_${date}.pdf`);
};
